### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [WhiteKr/UnitChanger#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by WhiteKr** [comment]
> If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

I never checked Issues in my GitHub. So sorry the answer is so late ;(
I do usually use TypeScript either so that will be so cool if you write a TypeScript type declaration file for my package.
I will much glad if you can help my package to can be used by more people.
Thank you for feeling interest on my package so much! 😄

**Comment by geopic** [comment]
No worries, I'll get started on it now :)
